In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
sent = [
    "I love red color",
    "I love blue color",
    "I love green color",
    "She drives a car",
    "She drives a bike",
    "She drives a bus",
]

In [35]:
sent

['I love red color',
 'I love blue color',
 'I love green color',
 'She drives a car',
 'She drives a bike',
 'She drives a bus']

In [36]:
## vocab size
voc_size = 10000

In [37]:
### one hot representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6200, 4584, 4193, 1036],
 [6200, 4584, 5159, 1036],
 [6200, 4584, 942, 1036],
 [1280, 1240, 5523, 5289],
 [1280, 1240, 5523, 4183],
 [1280, 1240, 5523, 2240]]

In [38]:
##word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [39]:
import numpy as np

In [40]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 6200 4584 4193 1036]
 [   0    0    0    0 6200 4584 5159 1036]
 [   0    0    0    0 6200 4584  942 1036]
 [   0    0    0    0 1280 1240 5523 5289]
 [   0    0    0    0 1280 1240 5523 4183]
 [   0    0    0    0 1280 1240 5523 2240]]


In [41]:
## feature representation

dim = 10 # dimension

In [48]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_len,)))
model.compile(optimizer="adam", loss="mse")

model.summary()

d:\Simple RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step


array([[[-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01612852,  0.0037426 ,  0.03185945, -0.0470872 ,
         -0.03497539, -0.02503668,  0.0034874 , -0.04107026,
          0.00869324,  0.01329497],
        [ 0.03418716,  0.0302887 ,  0.02158339, -0.00843854,
         -0.04012209, -0.00303836, -0.01565192, -0.03385027,
          0.01935582,  0.04289539],
        [ 0.01043607, -0.00064594,  0.01455767,  0.0

In [50]:
embedded_docs[0]

array([   0,    0,    0,    0, 6200, 4584, 4193, 1036], dtype=int32)

In [54]:
x = np.array([embedded_docs[0]]) 
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


array([[[-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01032714, -0.02953233, -0.03002586,  0.00182992,
          0.00427812, -0.02315271, -0.03485892,  0.01493993,
         -0.00635926, -0.01904482],
        [-0.01612852,  0.0037426 ,  0.03185945, -0.0470872 ,
         -0.03497539, -0.02503668,  0.0034874 , -0.04107026,
          0.00869324,  0.01329497],
        [ 0.03418716,  0.0302887 ,  0.02158339, -0.00843854,
         -0.04012209, -0.00303836, -0.01565192, -0.03385027,
          0.01935582,  0.04289539],
        [ 0.01043607, -0.00064594,  0.01455767,  0.0